#+TITLE: Notes
* Doom config Notes
** Telega config notes
[[https://github.com/zevlg/telega.el][Telega]] - telegram client
installation guide
verify all dependencies, or expect to discover them in the cmake step: [[https://zevlg.github.io/telega.el/][Telega Manual (v0.7.018)]]
#+begin_src sh
cd ~/.doom.d && git clone https://github.com/tdlib/td.git
cd ~/.doom.d/td
mkdir build && cd build
# this will reveal missing dependencies
cmake ../
# use as many cores as available, takes a couple mins
make -j4
sudo make install
# M-x telega-server build
# M-x telega
# cd ~/.doom.d && mv td tmp
#+end_src

** TODO dec 9 This is a todo to test magit-todos.
I still have to fix variable pitch font, and figure out what it takes to install a package.
** DONE Note to also check grammar check
** DONE Unsetting t and T:
Resolution: run a couple tests with the map! macro, and discover :after evil works pretty well.

I'm trying to unset the `t` and `T` keys. I look them up: `SPC h k t`, which returns:
```
Key Bindings
evil-snipe-override-local-mode-map <motion-state> t
evil-snipe-override-mode-map <motion-state> t
```
So I tried the following:
```
(undefine-key! evil-snipe-override-local-mode-map "t" "T")
(undefine-key! evil-snipe-override-mode-map "t" "T")
(map! :map 'evil-normal-state-map
      :n "t" #'transpose-chars
      :n "T" #'transpose-sexps)
```
and `M-x doom/reload`, but `t` and `T` are still bound. What else do I do?
* Inbox
** [2021-12-13 Mon 21:42] Notes from installing pass, the cmd line passwd manager
:PROPERTIES:
:ID:       60683684-f87d-445e-b686-8e760158d062
:END:
Easy!
1. Install pass https://www.passwordstore.org/
2. set up directory:
#+begin_src sh
gpg --list-keys #copy the last 8 chars from my gpg key
pass init "last-8-chars"
pass git init
#+end_src
3. migrate passwords from firefox:
#+begin_src sh
cd ~/play
hub clone unode/firefox_decrypt
cd firefox_deccrypt
python3 firefox_decrypt.py --format pass
pass ls
#+end_src
4. set up browser compatibility with the local password store
   install pass_ff, a firefox extension for managing pass https://addons.mozilla.org/en-US/firefox/addon/passff/
https://github.com/passff/passff#readme
install the host app
#+begin_src sh
curl -sSL github.com/passff/passff-host/releases/latest/download/install_host_app.sh | bash -s -- firefox
#+end_src
5. set up emacs integration:
   include pass https://github.com/NicolasPetton/pass
   M-x pass
6. todo: try using with firefox and emacs for awhile
[[orgit:~/.doom.d/][~/.doom.d/ (magit-status)]]
